name: build

on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Lint
      run: npm run lint

    - name: Publish the extension build output as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: dist

    - name: Publish the extension packages as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: packaged
        path: web-ext-artifacts

    - name: Publish a rolling latest release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: true
        title: Build from latest commit
        files: |
          web-ext-artifacts/macroll-*.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Create a signed extension for Firefox
      run: npx web-ext sign --api-key=${{ secrets.AMO_JWT_ISSUER }} --api-secret=${{ secrets.AMO_JWT_SECRET }} --source-dir dist

    - name: Publish the release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: |
          web-ext-artifacts/macroll-*.xpi
